/* eslint-disable */
// Generated by scripts/generate_typescript_sdk.py. DO NOT EDIT.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | Array<JsonValue>
  | { [key: string]: JsonValue }

export interface components {
  schemas: {
    "ApiKeyKind": "ordinary" | "worker"
    "ApiKeySortField": "created_at" | "updated_at" | "name"
    "ApiKeyStatus": "active" | "disabled" | "expired"
    "ApiKeySummary": {
      api_key_id: string
      created_at: string
      expires_at?: (string) | (null)
      kind?: components["schemas"]["ApiKeyKind"]
      last_used_at?: (string) | (null)
      name: string
      prefix: string
      status: components["schemas"]["ApiKeyStatus"]
      updated_at: string
      worker_id?: (string) | (null)
    }
    "ApiResponse_ApiKeySummary_": {
      data: components["schemas"]["ApiKeySummary"]
      request_id: string
    }
    "ApiResponse_ArtifactDownload_": {
      data: components["schemas"]["ArtifactDownload"]
      request_id: string
    }
    "ApiResponse_Artifact_": {
      data: components["schemas"]["Artifact"]
      request_id: string
    }
    "ApiResponse_BackendDetail_": {
      data: components["schemas"]["BackendDetail"]
      request_id: string
    }
    "ApiResponse_CallbackDeliveryDetail_": {
      data: components["schemas"]["CallbackDeliveryDetail"]
      request_id: string
    }
    "ApiResponse_CallbackTestData_": {
      data: components["schemas"]["CallbackTestData"]
      request_id: string
    }
    "ApiResponse_CreateApiKeyData_": {
      data: components["schemas"]["CreateApiKeyData"]
      request_id: string
    }
    "ApiResponse_CreateTaskData_": {
      data: components["schemas"]["CreateTaskData"]
      request_id: string
    }
    "ApiResponse_DashboardData_": {
      data: components["schemas"]["DashboardData"]
      request_id: string
    }
    "ApiResponse_DefaultCatalogInitializationData_": {
      data: components["schemas"]["DefaultCatalogInitializationData"]
      request_id: string
    }
    "ApiResponse_DeleteApiKeyData_": {
      data: components["schemas"]["DeleteApiKeyData"]
      request_id: string
    }
    "ApiResponse_HealthData_": {
      data: components["schemas"]["HealthData"]
      request_id: string
    }
    "ApiResponse_ParseResult_": {
      data: components["schemas"]["ParseResult"]
      request_id: string
    }
    "ApiResponse_ParserCapabilitiesData_": {
      data: components["schemas"]["ParserCapabilitiesData"]
      request_id: string
    }
    "ApiResponse_PipelineDefinition_": {
      data: components["schemas"]["PipelineDefinition"]
      request_id: string
    }
    "ApiResponse_PipelineValidationData_": {
      data: components["schemas"]["PipelineValidationData"]
      request_id: string
    }
    "ApiResponse_RenewStageLeaseData_": {
      data: components["schemas"]["RenewStageLeaseData"]
      request_id: string
    }
    "ApiResponse_RetentionRunData_": {
      data: components["schemas"]["RetentionRunData"]
      request_id: string
    }
    "ApiResponse_RotateApiKeyData_": {
      data: components["schemas"]["RotateApiKeyData"]
      request_id: string
    }
    "ApiResponse_StageDetail_": {
      data: components["schemas"]["StageDetail"]
      request_id: string
    }
    "ApiResponse_StageExecutionData_": {
      data: components["schemas"]["StageExecutionData"]
      request_id: string
    }
    "ApiResponse_SystemHealthData_": {
      data: components["schemas"]["SystemHealthData"]
      request_id: string
    }
    "ApiResponse_SystemInfoData_": {
      data: components["schemas"]["SystemInfoData"]
      request_id: string
    }
    "ApiResponse_SystemSettingsData_": {
      data: components["schemas"]["SystemSettingsData"]
      request_id: string
    }
    "ApiResponse_TaskDetail_": {
      data: components["schemas"]["TaskDetail"]
      request_id: string
    }
    "ApiResponse_UploadedFileDetail_": {
      data: components["schemas"]["UploadedFileDetail"]
      request_id: string
    }
    "ApiResponse_WorkerDetail_": {
      data: components["schemas"]["WorkerDetail"]
      request_id: string
    }
    "ApiResponse_WorkerHeartbeatData_": {
      data: components["schemas"]["WorkerHeartbeatData"]
      request_id: string
    }
    "ApiResponse_WorkerLeaseData_": {
      data: components["schemas"]["WorkerLeaseData"]
      request_id: string
    }
    "ApiResponse_WorkerReconcileData_": {
      data: components["schemas"]["WorkerReconcileData"]
      request_id: string
    }
    "ApiResponse_WorkerRegistrationData_": {
      data: components["schemas"]["WorkerRegistrationData"]
      request_id: string
    }
    "Artifact": {
      artifact_id: string
      created_at: string
      expires_at?: (string) | (null)
      filename: string
      metadata?: {
      [key: string]: JsonValue
    }
      mime_type: string
      sha256: string
      size_bytes: number
      storage_uri: string
      type: components["schemas"]["ArtifactType"]
    }
    "ArtifactDownload": {
      expires_at: string
      method?: "GET"
      url: string
    }
    "ArtifactSortField": "created_at" | "filename" | "size_bytes"
    "ArtifactType": "original" | "converted_document" | "extracted_image" | "keyframe" | "audio_track" | "subtitle" | "result_json" | "result_text" | "result_markdown" | "other"
    "BackendCapability": {
      maximum_concurrency: number
      media_categories?: Array<components["schemas"]["MediaCategory"]>
      mime_types?: Array<string>
      name: string
      runtimes: Array<components["schemas"]["DeviceRuntime"]>
      version: string
    }
    "BackendDetail": {
      backend_id: string
      capability: components["schemas"]["BackendCapability"]
      configuration?: {
      [key: string]: JsonValue
    }
      created_at: string
      default_timeout_seconds: number
      execution_mode: components["schemas"]["BackendExecutionMode"]
      maximum_attempts?: number
      remote_url?: (string) | (null)
      scheduling_weight?: number
      status: components["schemas"]["BackendStatus"]
      updated_at: string
    }
    "BackendExecutionMode": "local" | "remote"
    "BackendMetric": {
      average_duration_ms: number
      backend_id: string
      calls: number
      failures: number
      fallbacks: number
      timeouts: number
    }
    "BackendSelector": {
      fallbacks?: Array<string>
      preferred: string
      required_runtimes?: Array<components["schemas"]["DeviceRuntime"]>
    }
    "BackendSortField": "created_at" | "updated_at" | "name"
    "BackendStatus": "enabled" | "disabled" | "unhealthy"
    "BlockLocation": {
      bounding_box?: (components["schemas"]["BoundingBox"]) | (null)
      end_ms?: (number) | (null)
      page_number?: (number) | (null)
      sheet_name?: (string) | (null)
      slide_number?: (number) | (null)
      start_ms?: (number) | (null)
    }
    "Body_upload_file": {
      file: string
    }
    "Body_upload_stage_artifact": {
      artifact_type: components["schemas"]["ArtifactType"]
      file: string
      idempotency_key: string
      lease_token: string
    }
    "BoundingBox": {
      bottom: number
      left: number
      right: number
      top: number
    }
    "CallbackAttempt": {
      attempt_id: string
      attempt_number: number
      completed_at: string
      delivered: boolean
      delivery_id: string
      duration_ms: number
      error?: (components["schemas"]["ErrorDetail-Output"]) | (null)
      response_status_code?: (number) | (null)
      response_summary?: (string) | (null)
      sequence: number
      started_at: string
    }
    "CallbackAttemptSortField": "sequence" | "started_at" | "duration_ms"
    "CallbackConfig": {
      events: Array<components["schemas"]["CallbackEventType"]>
      secret?: (string) | (null)
      url: string
    }
    "CallbackDashboardSummary": {
      failed_deliveries: number
      pending_retries: number
      success_rate: number
      successful_deliveries: number
      total_deliveries: number
    }
    "CallbackDeliveryChangedEvent": {
      delivery_id: string
      status: components["schemas"]["CallbackDeliveryStatus"]
      task_id: string
      type: "callback.delivery_changed"
    }
    "CallbackDeliveryDetail": {
      attempt: number
      created_at: string
      delivery_id: string
      event: components["schemas"]["CallbackEvent"]
      maximum_attempts: number
      next_attempt_at?: (string) | (null)
      response_status_code?: (number) | (null)
      response_summary?: (string) | (null)
      status: components["schemas"]["CallbackDeliveryStatus"]
      target_url: string
      total_attempts: number
      updated_at: string
    }
    "CallbackDeliveryStatus": "pending" | "delivering" | "succeeded" | "retry_wait" | "failed" | "cancelled"
    "CallbackEvent": {
      event_id: string
      occurred_at: string
      payload: (components["schemas"]["TaskCreatedCallback"]) | (components["schemas"]["TaskRunningCallback"]) | (components["schemas"]["TaskProgressCallback"]) | (components["schemas"]["TaskSucceededCallback"]) | (components["schemas"]["TaskFailedCallback"]) | (components["schemas"]["TaskCancelledCallback"])
      schema_version: string
      task_id: string
    }
    "CallbackEventType": "task.created" | "task.running" | "task.progress" | "task.succeeded" | "task.failed" | "task.cancelled"
    "CallbackSortField": "created_at" | "updated_at" | "status"
    "CallbackTestData": {
      delivered: boolean
      duration_ms: number
      error?: (components["schemas"]["ErrorDetail-Output"]) | (null)
      response_status_code?: (number) | (null)
    }
    "CallbackTestRequest": {
      metadata?: {
      [key: string]: JsonValue
    }
      secret?: (string) | (null)
      url: string
    }
    "CompleteStageRequest": {
      error?: (components["schemas"]["ErrorDetail-Input"]) | (null)
      lease_token: string
      result_uri?: (string) | (null)
      status: "succeeded" | "failed"
      worker_id: string
    }
    "ComponentHealth": {
      checked_at: string
      healthy: boolean
      message?: (string) | (null)
      name: string
    }
    "ContentMetadata": {
      attributes?: {
      [key: string]: JsonValue
    }
      duration_ms?: (number) | (null)
      height_pixels?: (number) | (null)
      language?: (string) | (null)
      page_count?: (number) | (null)
      title?: (string) | (null)
      width_pixels?: (number) | (null)
    }
    "CreateApiKeyData": {
      api_key: string
      summary: components["schemas"]["ApiKeySummary"]
    }
    "CreateApiKeyRequest": {
      expires_at?: (string) | (null)
      kind?: components["schemas"]["ApiKeyKind"]
      name: string
      worker_id?: (string) | (null)
    }
    "CreateBackendRequest": {
      capability: components["schemas"]["BackendCapability"]
      configuration?: {
      [key: string]: JsonValue
    }
      default_timeout_seconds: number
      enabled?: boolean
      execution_mode: components["schemas"]["BackendExecutionMode"]
      maximum_attempts?: number
      remote_url?: (string) | (null)
      scheduling_weight?: number
    }
    "CreatePipelineRequest": {
      media_categories: Array<components["schemas"]["MediaCategory"]>
      mime_types?: Array<string>
      name: string
      pipeline_id: string
      routing_priority?: number
      stages: Array<components["schemas"]["PipelineStageDefinition-Input"]>
    }
    "CreateTaskData": {
      created_at: string
      estimated_wait_seconds?: (number) | (null)
      status: components["schemas"]["TaskStatus"]
      task_id: string
    }
    "CreateTaskRequest": {
      callback?: (components["schemas"]["CallbackConfig"]) | (null)
      client_reference?: (string) | (null)
      options?: components["schemas"]["TaskOptions"]
      source: (components["schemas"]["UploadedFileSource"]) | (components["schemas"]["UrlSource"]) | (components["schemas"]["ObjectStorageSource"]) | (components["schemas"]["TextSource"])
    }
    "DashboardData": {
      backends?: Array<components["schemas"]["BackendMetric"]>
      callbacks: components["schemas"]["CallbackDashboardSummary"]
      generated_at: string
      runtimes?: Array<components["schemas"]["RuntimeMetric"]>
      series?: Array<components["schemas"]["NamedTimeSeries"]>
      storage: components["schemas"]["StorageDashboardSummary"]
      tasks: components["schemas"]["TaskDashboardSummary"]
      workers: components["schemas"]["WorkerDashboardSummary"]
    }
    "DefaultCatalogAction": "created" | "published" | "unchanged" | "draft_unavailable"
    "DefaultCatalogInitializationData": {
      backend_ids_created?: Array<string>
      backend_ids_existing?: Array<string>
      pipelines: Array<components["schemas"]["DefaultPipelineInitialization"]>
    }
    "DefaultPipelineInitialization": {
      action: components["schemas"]["DefaultCatalogAction"]
      pipeline_id: string
      status: components["schemas"]["PipelineStatus"]
      version: number
      violations?: Array<components["schemas"]["PipelineValidationViolation"]>
    }
    "DeleteApiKeyData": {
      api_key_id: string
      deleted: boolean
    }
    "DeviceInfo": {
      device_id: string
      driver_version?: (string) | (null)
      model: string
      runtime: components["schemas"]["DeviceRuntime"]
      runtime_version?: (string) | (null)
      total_memory_bytes?: (number) | (null)
      vendor: components["schemas"]["HardwareVendor"]
    }
    "DeviceRequirement": {
      minimum_memory_bytes?: (number) | (null)
      runtimes?: Array<components["schemas"]["DeviceRuntime"]>
      strategy?: components["schemas"]["SchedulingStrategy"]
      worker_labels?: {
      [key: string]: string
    }
    }
    "DeviceRuntime": "cpu" | "cuda" | "ascend" | "mlu" | "dcu" | "musa" | "xpu"
    "DeviceUsage": {
      device_id: string
      memory_total_bytes?: (number) | (null)
      memory_used_bytes?: (number) | (null)
      temperature_celsius?: (number) | (null)
      utilization_percent?: (number) | (null)
    }
    "ErrorCode": "VALIDATION_ERROR" | "AUTHENTICATION_FAILED" | "API_KEY_EXPIRED" | "NOT_FOUND" | "CONFLICT" | "UNSUPPORTED_MEDIA_TYPE" | "FILE_TOO_LARGE" | "TASK_NOT_CANCELLABLE" | "WORKER_NOT_AVAILABLE" | "BACKEND_NOT_AVAILABLE" | "TIMEOUT" | "RATE_LIMITED" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR"
    "ErrorDetail-Input": {
      code: components["schemas"]["ErrorCode"]
      context?: {
      [key: string]: JsonValue
    }
      field_violations?: Array<components["schemas"]["FieldViolation"]>
      message: string
      retryable?: boolean
    }
    "ErrorDetail-Output": {
      code: components["schemas"]["ErrorCode"]
      context?: {
      [key: string]: JsonValue
    }
      field_violations?: Array<components["schemas"]["FieldViolation"]>
      message: string
      retryable?: boolean
    }
    "ErrorResponse": {
      error: components["schemas"]["ErrorDetail-Output"]
      request_id: string
    }
    "EventEnvelope": {
      event_id: string
      occurred_at: string
      payload: (components["schemas"]["TaskCreatedEvent"]) | (components["schemas"]["TaskRoutedEvent"]) | (components["schemas"]["TaskStatusChangedEvent"]) | (components["schemas"]["TaskProgressUpdatedEvent"]) | (components["schemas"]["WorkerStatusChangedEvent"]) | (components["schemas"]["CallbackDeliveryChangedEvent"]) | (components["schemas"]["SystemAlertEvent"])
      schema_version: string
    }
    "EventSortField": "occurred_at" | "type"
    "FieldViolation": {
      field: string
      reason: string
    }
    "HardwareVendor": "generic" | "nvidia" | "huawei" | "cambricon" | "hygon" | "moore_threads" | "kunlun"
    "HeadingBlock": {
      block_id: string
      level: number
      location?: (components["schemas"]["BlockLocation"]) | (null)
      metadata?: {
      [key: string]: JsonValue
    }
      text: string
      type: "heading"
    }
    "HealthData": {
      status: components["schemas"]["HealthStatus"]
      timestamp: string
      version: string
    }
    "HealthStatus": "healthy" | "degraded" | "unhealthy"
    "ImageBlock": {
      artifact_id: string
      block_id: string
      caption?: (string) | (null)
      location?: (components["schemas"]["BlockLocation"]) | (null)
      metadata?: {
      [key: string]: JsonValue
    }
      ocr_text?: (string) | (null)
      type: "image"
    }
    "InitializeDefaultsRequest": {
      include_builtin_backends?: boolean
      publish_valid_pipelines?: boolean
    }
    "JsonValue-Input": JsonValue
    "JsonValue-Output": JsonValue
    "KeyframeBlock": {
      artifact_id: string
      block_id: string
      caption?: (string) | (null)
      metadata?: {
      [key: string]: JsonValue
    }
      ocr_text?: (string) | (null)
      timestamp_ms: number
      type: "keyframe"
    }
    "LeasedStage": {
      attempt: number
      backend_candidates: Array<string>
      backend_id: string
      backend_name: string
      backend_version: string
      device_id?: (string) | (null)
      lease_expires_at: string
      lease_token: string
      maximum_attempts: number
      parameters?: {
      [key: string]: JsonValue
    }
      runtime: components["schemas"]["DeviceRuntime"]
      source: (components["schemas"]["UploadedFileSource"]) | (components["schemas"]["UrlSource"]) | (components["schemas"]["ObjectStorageSource"]) | (components["schemas"]["TextSource"])
      source_metadata: components["schemas"]["SourceMetadata"]
      stage_id: string
      stage_name: string
      task_id: string
      task_options: components["schemas"]["TaskOptions"]
      timeout_seconds: number
      trace_context?: (components["schemas"]["TraceContext"]) | (null)
    }
    "LinkBlock": {
      block_id: string
      metadata?: {
      [key: string]: JsonValue
    }
      text?: (string) | (null)
      type: "link"
      url: string
    }
    "ListResponse_ApiKeySummary_": {
      items?: Array<components["schemas"]["ApiKeySummary"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_Artifact_": {
      items?: Array<components["schemas"]["Artifact"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_BackendDetail_": {
      items?: Array<components["schemas"]["BackendDetail"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_CallbackAttempt_": {
      items?: Array<components["schemas"]["CallbackAttempt"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_CallbackDeliveryDetail_": {
      items?: Array<components["schemas"]["CallbackDeliveryDetail"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_EventEnvelope_": {
      items?: Array<components["schemas"]["EventEnvelope"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_PipelineDefinition_": {
      items?: Array<components["schemas"]["PipelineDefinition"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_StageDetail_": {
      items?: Array<components["schemas"]["StageDetail"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_TaskDetail_": {
      items?: Array<components["schemas"]["TaskDetail"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "ListResponse_WorkerDetail_": {
      items?: Array<components["schemas"]["WorkerDetail"]>
      page: components["schemas"]["PageInfo"]
      request_id: string
    }
    "MediaCategory": "document" | "image" | "audio" | "video" | "web" | "text"
    "MetricInterval": "1m" | "5m" | "1h" | "1d"
    "NamedTimeSeries": {
      name: string
      points?: Array<components["schemas"]["TimeSeriesPoint"]>
      unit: string
    }
    "ObjectStorageSource": {
      type: "object_storage"
      uri: string
      version_id?: (string) | (null)
    }
    "PageInfo": {
      has_more: boolean
      next_cursor?: (string) | (null)
    }
    "ParseFeatures": {
      extract_images?: boolean
      extract_keyframes?: boolean
      extract_tables?: boolean
      extract_text?: boolean
      generate_captions?: boolean
      run_ocr?: boolean
      transcribe_audio?: boolean
    }
    "ParseResult": {
      artifacts?: Array<components["schemas"]["Artifact"]>
      blocks?: Array<(components["schemas"]["TextBlock"]) | (components["schemas"]["HeadingBlock"]) | (components["schemas"]["TableBlock"]) | (components["schemas"]["ImageBlock"]) | (components["schemas"]["TranscriptBlock"]) | (components["schemas"]["KeyframeBlock"]) | (components["schemas"]["LinkBlock"])>
      created_at: string
      metadata: components["schemas"]["ContentMetadata"]
      schema_version: string
      source: components["schemas"]["SourceMetadata"]
      task_id: string
      warnings?: Array<components["schemas"]["ParseWarning"]>
    }
    "ParseWarning": {
      code: string
      context?: {
      [key: string]: JsonValue
    }
      message: string
      stage_id?: (string) | (null)
    }
    "ParserCapabilitiesData": {
      backends: Array<string>
      maximum_upload_bytes: number
      media_categories: Array<components["schemas"]["MediaCategory"]>
      mime_types: Array<string>
      pipelines: Array<string>
      runtimes: Array<components["schemas"]["RuntimeCapability"]>
      schema_version: string
    }
    "PipelineDefinition": {
      created_at: string
      media_categories: Array<components["schemas"]["MediaCategory"]>
      mime_types?: Array<string>
      name: string
      pipeline_id: string
      published_at?: (string) | (null)
      routing_priority?: number
      stages: Array<components["schemas"]["PipelineStageDefinition-Output"]>
      status: components["schemas"]["PipelineStatus"]
      version: number
    }
    "PipelineSortField": "created_at" | "updated_at" | "name" | "version"
    "PipelineStageDefinition-Input": {
      backend: components["schemas"]["BackendSelector"]
      depends_on?: Array<string>
      name: string
      optional?: boolean
      parameters?: {
      [key: string]: JsonValue
    }
      retry?: components["schemas"]["RetryPolicy"]
      timeout_seconds: number
    }
    "PipelineStageDefinition-Output": {
      backend: components["schemas"]["BackendSelector"]
      depends_on?: Array<string>
      name: string
      optional?: boolean
      parameters?: {
      [key: string]: JsonValue
    }
      retry?: components["schemas"]["RetryPolicy"]
      timeout_seconds: number
    }
    "PipelineStatus": "draft" | "published" | "disabled" | "archived"
    "PipelineTestOptions": {
      backend_name?: (string) | (null)
      device?: components["schemas"]["DeviceRequirement"]
      features?: components["schemas"]["ParseFeatures"]
      priority?: number
      timeout_seconds?: (number) | (null)
    }
    "PipelineTestRequest": {
      client_reference?: (string) | (null)
      options?: components["schemas"]["PipelineTestOptions"]
      source: (components["schemas"]["UploadedFileSource"]) | (components["schemas"]["UrlSource"]) | (components["schemas"]["ObjectStorageSource"]) | (components["schemas"]["TextSource"])
    }
    "PipelineValidationData": {
      valid: boolean
      violations?: Array<components["schemas"]["PipelineValidationViolation"]>
    }
    "PipelineValidationViolation": {
      location: string
      message: string
    }
    "RenewStageLeaseData": {
      lease_expires_at: string
      stage_id: string
    }
    "RenewStageLeaseRequest": {
      lease_token: string
      worker_id: string
    }
    "RetentionRunData": {
      artifacts_selected: number
      artifacts_skipped_active: number
      cutoff_time: string
      dry_run: boolean
      events_selected: number
      storage_delete_failures: number
      uploaded_files_selected: number
      uploaded_files_skipped_active: number
    }
    "RetryPolicy": {
      initial_delay_seconds?: number
      maximum_attempts?: number
      maximum_delay_seconds?: number
      multiplier?: number
    }
    "RotateApiKeyData": {
      api_key: string
      previous_key_valid_until?: (string) | (null)
      summary: components["schemas"]["ApiKeySummary"]
    }
    "RunRetentionRequest": {
      dry_run?: boolean
      maximum_records?: number
    }
    "RuntimeCapability": {
      available_devices: number
      available_workers: number
      runtime: components["schemas"]["DeviceRuntime"]
      vendor: components["schemas"]["HardwareVendor"]
    }
    "RuntimeMetric": {
      average_utilization_percent?: (number) | (null)
      devices: number
      memory_total_bytes?: (number) | (null)
      memory_used_bytes?: (number) | (null)
      runtime: components["schemas"]["DeviceRuntime"]
      workers: number
    }
    "SchedulingStrategy": "auto" | "prefer" | "require"
    "SettingKey": "maximum_upload_bytes" | "maximum_result_json_bytes" | "callback_maximum_attempts"
    "SettingSource": "deployment" | "database"
    "SortDirection": "asc" | "desc"
    "SourceMetadata": {
      attributes?: {
      [key: string]: JsonValue
    }
      filename?: (string) | (null)
      media_category: components["schemas"]["MediaCategory"]
      mime_type: string
      sha256?: (string) | (null)
      size_bytes?: (number) | (null)
    }
    "StageDetail": {
      attempt?: number
      backend_candidates?: Array<string>
      backend_id?: (string) | (null)
      backend_version?: (string) | (null)
      completed_at?: (string) | (null)
      completion_device_id?: (string) | (null)
      completion_worker_id?: (string) | (null)
      created_at: string
      depends_on?: Array<string>
      device_id?: (string) | (null)
      error?: (components["schemas"]["ErrorDetail-Output"]) | (null)
      maximum_attempts?: number
      name: string
      optional?: boolean
      position?: number
      progress_percent?: number
      required_runtimes?: Array<components["schemas"]["DeviceRuntime"]>
      result_uri?: (string) | (null)
      runtime?: (components["schemas"]["DeviceRuntime"]) | (null)
      stage_id: string
      started_at?: (string) | (null)
      status: components["schemas"]["StageStatus"]
      timeout_seconds?: (number) | (null)
      worker_id?: (string) | (null)
    }
    "StageExecutionData": {
      lease_expires_at?: (string) | (null)
      progress_percent: number
      stage_id: string
      stage_status: components["schemas"]["StageStatus"]
      task_id: string
      task_status: components["schemas"]["TaskStatus"]
    }
    "StageProgressRequest": {
      lease_token: string
      progress_percent: number
      worker_id: string
    }
    "StageSortField": "position" | "created_at"
    "StageStatus": "pending" | "leased" | "running" | "succeeded" | "failed" | "cancelled" | "skipped"
    "StartStageRequest": {
      lease_token: string
      worker_id: string
    }
    "StorageDashboardSummary": {
      artifact_bytes: number
      objects: number
      original_bytes: number
      result_bytes: number
    }
    "SystemAlertEvent": {
      code: string
      error?: (components["schemas"]["ErrorDetail-Output"]) | (null)
      message: string
      severity: "info" | "warning" | "critical"
      type: "system.alert"
    }
    "SystemHealthData": {
      components: Array<components["schemas"]["ComponentHealth"]>
      healthy: boolean
    }
    "SystemInfoData": {
      api_version: string
      build_commit?: (string) | (null)
      build_time?: (string) | (null)
      name: string
      result_schema_version: string
      version: string
    }
    "SystemSetting": {
      key: components["schemas"]["SettingKey"]
      source: components["schemas"]["SettingSource"]
      updated_at?: (string) | (null)
      value: JsonValue
    }
    "SystemSettingsData": {
      settings: Array<components["schemas"]["SystemSetting"]>
    }
    "TableBlock": {
      block_id: string
      location?: (components["schemas"]["BlockLocation"]) | (null)
      metadata?: {
      [key: string]: JsonValue
    }
      rows: Array<Array<string>>
      type: "table"
    }
    "TaskCancelledCallback": {
      cancelled_at: string
      reason?: (string) | (null)
      type: "task.cancelled"
    }
    "TaskCreatedCallback": {
      created_at: string
      type: "task.created"
    }
    "TaskCreatedEvent": {
      task_id: string
      type: "task.created"
    }
    "TaskDashboardSummary": {
      average_execution_ms: number
      average_wait_ms: number
      cancelled_tasks: number
      failed_tasks: number
      p50_execution_ms: number
      p95_execution_ms: number
      p99_execution_ms: number
      pending_tasks: number
      running_tasks: number
      succeeded_tasks: number
      success_rate: number
      total_tasks: number
    }
    "TaskDetail": {
      client_reference?: (string) | (null)
      completed_at?: (string) | (null)
      created_at: string
      error?: (components["schemas"]["ErrorDetail-Output"]) | (null)
      options: components["schemas"]["TaskOptions"]
      pipeline_id?: (string) | (null)
      pipeline_version?: (number) | (null)
      progress_percent?: number
      result_uri?: (string) | (null)
      source: (components["schemas"]["UploadedFileSource"]) | (components["schemas"]["UrlSource"]) | (components["schemas"]["ObjectStorageSource"]) | (components["schemas"]["TextSource"])
      source_metadata?: (components["schemas"]["SourceMetadata"]) | (null)
      stages?: Array<components["schemas"]["StageDetail"]>
      started_at?: (string) | (null)
      status: components["schemas"]["TaskStatus"]
      task_id: string
    }
    "TaskFailedCallback": {
      error: components["schemas"]["ErrorDetail-Output"]
      failed_at: string
      type: "task.failed"
    }
    "TaskOptions": {
      backend_name?: (string) | (null)
      device?: components["schemas"]["DeviceRequirement"]
      features?: components["schemas"]["ParseFeatures"]
      pipeline_id?: (string) | (null)
      pipeline_version?: (number) | (null)
      priority?: number
      timeout_seconds?: (number) | (null)
    }
    "TaskProgressCallback": {
      progress_percent: number
      stage_id?: (string) | (null)
      stage_name?: (string) | (null)
      type: "task.progress"
      updated_at: string
    }
    "TaskProgressUpdatedEvent": {
      progress_percent: number
      stage_id?: (string) | (null)
      stage_status?: (components["schemas"]["StageStatus"]) | (null)
      task_id: string
      type: "task.progress_updated"
    }
    "TaskRoutedEvent": {
      pipeline_id: string
      pipeline_version: number
      stage_ids: Array<string>
      task_id: string
      type: "task.routed"
    }
    "TaskRunningCallback": {
      started_at: string
      type: "task.running"
    }
    "TaskSortField": "created_at" | "updated_at" | "priority"
    "TaskStatus": "pending" | "leased" | "running" | "succeeded" | "failed" | "cancelled"
    "TaskStatusChangedEvent": {
      current_status: components["schemas"]["TaskStatus"]
      previous_status: components["schemas"]["TaskStatus"]
      task_id: string
      type: "task.status_changed"
    }
    "TaskSucceededCallback": {
      completed_at: string
      result_uri?: (string) | (null)
      type: "task.succeeded"
    }
    "TextBlock": {
      block_id: string
      location?: (components["schemas"]["BlockLocation"]) | (null)
      metadata?: {
      [key: string]: JsonValue
    }
      text: string
      type: "text"
    }
    "TextSource": {
      filename?: (string) | (null)
      mime_type?: string
      text: string
      type: "text"
    }
    "TimeSeriesPoint": {
      timestamp: string
      value: number
    }
    "TraceContext": {
      traceparent: string
      tracestate?: (string) | (null)
    }
    "TranscriptBlock": {
      block_id: string
      end_ms: number
      language?: (string) | (null)
      metadata?: {
      [key: string]: JsonValue
    }
      speaker?: (string) | (null)
      start_ms: number
      text: string
      type: "transcript"
    }
    "UpdateApiKeyRequest": {
      enabled?: (boolean) | (null)
      expires_at?: (string) | (null)
      name?: (string) | (null)
    }
    "UpdateBackendRequest": {
      configuration?: ({
      [key: string]: JsonValue
    }) | (null)
      default_timeout_seconds?: (number) | (null)
      enabled?: (boolean) | (null)
      maximum_attempts?: (number) | (null)
      scheduling_weight?: (number) | (null)
    }
    "UpdateSetting": {
      key: components["schemas"]["SettingKey"]
      value: JsonValue
    }
    "UpdateSettingsRequest": {
      settings: Array<components["schemas"]["UpdateSetting"]>
    }
    "UpdateWorkerRequest": {
      draining?: (boolean) | (null)
      enabled?: (boolean) | (null)
      labels?: ({
      [key: string]: string
    }) | (null)
      maximum_concurrency?: (number) | (null)
      scheduling_weight?: (number) | (null)
    }
    "UploadedFileDetail": {
      created_at: string
      expires_at?: (string) | (null)
      file_id: string
      filename: string
      media_category: components["schemas"]["MediaCategory"]
      mime_type: string
      sha256: string
      size_bytes: number
    }
    "UploadedFileSource": {
      file_id: string
      type: "uploaded_file"
    }
    "UrlSource": {
      type: "url"
      url: string
    }
    "WorkerDashboardSummary": {
      busy_workers: number
      draining_workers: number
      offline_workers: number
      online_workers: number
      total_concurrency: number
      total_workers: number
      unhealthy_workers: number
      used_concurrency: number
    }
    "WorkerDetail": {
      backends: Array<components["schemas"]["BackendCapability"]>
      created_at: string
      device_usage?: Array<components["schemas"]["DeviceUsage"]>
      devices: Array<components["schemas"]["DeviceInfo"]>
      enabled: boolean
      hostname: string
      labels?: {
      [key: string]: string
    }
      last_heartbeat_at?: (string) | (null)
      maximum_concurrency: number
      name: string
      resources?: (components["schemas"]["WorkerResourceUsage"]) | (null)
      scheduling_weight: number
      status: components["schemas"]["WorkerStatus"]
      updated_at: string
      version: string
      worker_id: string
    }
    "WorkerHealthCheck": {
      healthy: boolean
      message?: (string) | (null)
      name: string
    }
    "WorkerHeartbeatData": {
      accepted: boolean
      next_heartbeat_seconds: number
      should_drain?: boolean
    }
    "WorkerHeartbeatRequest": {
      devices?: Array<components["schemas"]["DeviceUsage"]>
      resources: components["schemas"]["WorkerResourceUsage"]
      sequence: number
      status: components["schemas"]["WorkerStatus"]
      timestamp: string
      worker_id: string
    }
    "WorkerLeaseData": {
      leases?: Array<components["schemas"]["LeasedStage"]>
    }
    "WorkerLeaseRequest": {
      available_slots: number
      wait_seconds?: number
      worker_id: string
    }
    "WorkerReconcileData": {
      offline_worker_ids?: Array<string>
      requeued_stage_ids?: Array<string>
    }
    "WorkerRegistrationData": {
      accepted: boolean
      heartbeat_interval_seconds: number
      lease_duration_seconds: number
      registered_at: string
      worker_id: string
    }
    "WorkerRegistrationRequest": {
      backends?: Array<components["schemas"]["BackendCapability"]>
      devices: Array<components["schemas"]["DeviceInfo"]>
      hostname: string
      labels?: {
      [key: string]: string
    }
      maximum_concurrency: number
      name: string
      version: string
      worker_id: string
    }
    "WorkerResourceUsage": {
      cpu_percent: number
      health_checks?: Array<components["schemas"]["WorkerHealthCheck"]>
      leased_tasks: number
      memory_total_bytes: number
      memory_used_bytes: number
      running_tasks: number
    }
    "WorkerSortField": "created_at" | "updated_at" | "name"
    "WorkerStatus": "online" | "busy" | "draining" | "offline" | "unhealthy"
    "WorkerStatusChangedEvent": {
      current_status: components["schemas"]["WorkerStatus"]
      previous_status?: (components["schemas"]["WorkerStatus"]) | (null)
      type: "worker.status_changed"
      worker_id: string
    }
  }
}

export interface operations {
  "cancel_task": {
    parameters: {
      path: {
        task_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_TaskDetail_"]
  }
  "complete_stage": {
    parameters: {
      path: {
        stage_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["CompleteStageRequest"]
    response: components["schemas"]["ApiResponse_StageExecutionData_"]
  }
  "create_api_key": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["CreateApiKeyRequest"]
    response: components["schemas"]["ApiResponse_CreateApiKeyData_"]
  }
  "create_backend": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["CreateBackendRequest"]
    response: components["schemas"]["ApiResponse_BackendDetail_"]
  }
  "create_pipeline": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["CreatePipelineRequest"]
    response: components["schemas"]["ApiResponse_PipelineDefinition_"]
  }
  "create_task": {
    parameters: {
      path: {}
      query: {}
      header: {
        "Idempotency-Key"?: (string) | (null)
      }
    }
    requestBody: components["schemas"]["CreateTaskRequest"]
    response: components["schemas"]["ApiResponse_CreateTaskData_"]
  }
  "create_task_artifact_download_url": {
    parameters: {
      path: {
        task_id: string
        artifact_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_ArtifactDownload_"]
  }
  "delete_api_key": {
    parameters: {
      path: {
        api_key_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_DeleteApiKeyData_"]
  }
  "download_task_artifact": {
    parameters: {
      path: {
        task_id: string
        artifact_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: Blob
  }
  "download_task_result": {
    parameters: {
      path: {
        task_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: Blob
  }
  "download_uploaded_file": {
    parameters: {
      path: {
        file_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: Blob
  }
  "download_worker_source_file": {
    parameters: {
      path: {
        worker_id: string
        file_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: Blob
  }
  "drain_worker_self": {
    parameters: {
      path: {
        worker_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_WorkerDetail_"]
  }
  "get_api_key": {
    parameters: {
      path: {
        api_key_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_ApiKeySummary_"]
  }
  "get_backend": {
    parameters: {
      path: {
        backend_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_BackendDetail_"]
  }
  "get_callback_delivery": {
    parameters: {
      path: {
        delivery_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_CallbackDeliveryDetail_"]
  }
  "get_capabilities": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_ParserCapabilitiesData_"]
  }
  "get_dashboard_summary": {
    parameters: {
      path: {}
      query: {
        start_time?: (string) | (null)
        end_time?: (string) | (null)
        interval?: components["schemas"]["MetricInterval"]
        pipeline_id?: (string) | (null)
        backend_id?: (string) | (null)
        worker_id?: (string) | (null)
        runtime?: (components["schemas"]["DeviceRuntime"]) | (null)
        media_category?: (components["schemas"]["MediaCategory"]) | (null)
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_DashboardData_"]
  }
  "get_health": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_HealthData_"]
  }
  "get_metrics": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: Blob
  }
  "get_pipeline": {
    parameters: {
      path: {
        pipeline_id: string
        version: number
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_PipelineDefinition_"]
  }
  "get_readiness": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_SystemHealthData_"]
  }
  "get_system_info": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_SystemInfoData_"]
  }
  "get_system_settings": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_SystemSettingsData_"]
  }
  "get_task": {
    parameters: {
      path: {
        task_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_TaskDetail_"]
  }
  "get_task_result": {
    parameters: {
      path: {
        task_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_ParseResult_"]
  }
  "get_task_stage": {
    parameters: {
      path: {
        task_id: string
        stage_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_StageDetail_"]
  }
  "get_uploaded_file": {
    parameters: {
      path: {
        file_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_UploadedFileDetail_"]
  }
  "get_worker": {
    parameters: {
      path: {
        worker_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_WorkerDetail_"]
  }
  "heartbeat_worker": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["WorkerHeartbeatRequest"]
    response: components["schemas"]["ApiResponse_WorkerHeartbeatData_"]
  }
  "initialize_default_catalog": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["InitializeDefaultsRequest"]
    response: components["schemas"]["ApiResponse_DefaultCatalogInitializationData_"]
  }
  "lease_stages": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["WorkerLeaseRequest"]
    response: components["schemas"]["ApiResponse_WorkerLeaseData_"]
  }
  "list_api_keys": {
    parameters: {
      path: {}
      query: {
        kinds?: (Array<components["schemas"]["ApiKeyKind"]>) | (null)
        statuses?: (Array<components["schemas"]["ApiKeyStatus"]>) | (null)
        name_contains?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["ApiKeySortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_ApiKeySummary_"]
  }
  "list_backends": {
    parameters: {
      path: {}
      query: {
        statuses?: (Array<components["schemas"]["BackendStatus"]>) | (null)
        runtimes?: (Array<components["schemas"]["DeviceRuntime"]>) | (null)
        media_category?: (components["schemas"]["MediaCategory"]) | (null)
        execution_mode?: (components["schemas"]["BackendExecutionMode"]) | (null)
        name_contains?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["BackendSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_BackendDetail_"]
  }
  "list_callback_attempts": {
    parameters: {
      path: {
        delivery_id: string
      }
      query: {
        delivered?: (boolean) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["CallbackAttemptSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_CallbackAttempt_"]
  }
  "list_callback_deliveries": {
    parameters: {
      path: {}
      query: {
        statuses?: (Array<components["schemas"]["CallbackDeliveryStatus"]>) | (null)
        task_id?: (string) | (null)
        event_types?: (Array<components["schemas"]["CallbackEventType"]>) | (null)
        created_after?: (string) | (null)
        created_before?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["CallbackSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_CallbackDeliveryDetail_"]
  }
  "list_events": {
    parameters: {
      path: {}
      query: {
        types?: (Array<string>) | (null)
        task_id?: (string) | (null)
        worker_id?: (string) | (null)
        last_event_id?: (string) | (null)
        limit?: number
        sort_by?: components["schemas"]["EventSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_EventEnvelope_"]
  }
  "list_pipelines": {
    parameters: {
      path: {}
      query: {
        statuses?: (Array<components["schemas"]["PipelineStatus"]>) | (null)
        media_category?: (components["schemas"]["MediaCategory"]) | (null)
        name_contains?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["PipelineSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_PipelineDefinition_"]
  }
  "list_task_artifacts": {
    parameters: {
      path: {
        task_id: string
      }
      query: {
        types?: (Array<components["schemas"]["ArtifactType"]>) | (null)
        mime_type?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["ArtifactSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_Artifact_"]
  }
  "list_task_events": {
    parameters: {
      path: {
        task_id: string
      }
      query: {
        types?: (Array<string>) | (null)
        task_id?: (string) | (null)
        worker_id?: (string) | (null)
        last_event_id?: (string) | (null)
        limit?: number
        sort_by?: components["schemas"]["EventSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_EventEnvelope_"]
  }
  "list_task_stages": {
    parameters: {
      path: {
        task_id: string
      }
      query: {
        statuses?: (Array<components["schemas"]["StageStatus"]>) | (null)
        backend_id?: (string) | (null)
        worker_id?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["StageSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_StageDetail_"]
  }
  "list_tasks": {
    parameters: {
      path: {}
      query: {
        statuses?: (Array<components["schemas"]["TaskStatus"]>) | (null)
        media_category?: (components["schemas"]["MediaCategory"]) | (null)
        pipeline_id?: (string) | (null)
        backend_name?: (string) | (null)
        runtime?: (components["schemas"]["DeviceRuntime"]) | (null)
        created_after?: (string) | (null)
        created_before?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["TaskSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_TaskDetail_"]
  }
  "list_workers": {
    parameters: {
      path: {}
      query: {
        statuses?: (Array<components["schemas"]["WorkerStatus"]>) | (null)
        runtimes?: (Array<components["schemas"]["DeviceRuntime"]>) | (null)
        labels?: (Array<string>) | (null)
        name_contains?: (string) | (null)
        limit?: number
        cursor?: (string) | (null)
        sort_by?: components["schemas"]["WorkerSortField"]
        sort_direction?: components["schemas"]["SortDirection"]
      }
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ListResponse_WorkerDetail_"]
  }
  "publish_pipeline": {
    parameters: {
      path: {
        pipeline_id: string
        version: number
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_PipelineDefinition_"]
  }
  "reconcile_workers": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_WorkerReconcileData_"]
  }
  "register_worker": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["WorkerRegistrationRequest"]
    response: components["schemas"]["ApiResponse_WorkerRegistrationData_"]
  }
  "renew_stage_lease": {
    parameters: {
      path: {
        stage_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["RenewStageLeaseRequest"]
    response: components["schemas"]["ApiResponse_RenewStageLeaseData_"]
  }
  "retry_callback_delivery": {
    parameters: {
      path: {
        delivery_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_CallbackDeliveryDetail_"]
  }
  "retry_task": {
    parameters: {
      path: {
        task_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_TaskDetail_"]
  }
  "rotate_api_key": {
    parameters: {
      path: {
        api_key_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_RotateApiKeyData_"]
  }
  "route_task": {
    parameters: {
      path: {
        task_id: string
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_TaskDetail_"]
  }
  "run_retention_cleanup": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["RunRetentionRequest"]
    response: components["schemas"]["ApiResponse_RetentionRunData_"]
  }
  "start_stage": {
    parameters: {
      path: {
        stage_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["StartStageRequest"]
    response: components["schemas"]["ApiResponse_StageExecutionData_"]
  }
  "stream_events": {
    parameters: {
      path: {}
      query: {
        types?: (Array<string>) | (null)
        task_id?: (string) | (null)
        worker_id?: (string) | (null)
        last_event_id?: (string) | (null)
      }
      header: {
        "Last-Event-ID"?: (string) | (null)
      }
    }
    requestBody: undefined
    response: string
  }
  "stream_task_events": {
    parameters: {
      path: {
        task_id: string
      }
      query: {
        types?: (Array<string>) | (null)
        task_id?: (string) | (null)
        worker_id?: (string) | (null)
        last_event_id?: (string) | (null)
      }
      header: {
        "Last-Event-ID"?: (string) | (null)
      }
    }
    requestBody: undefined
    response: string
  }
  "test_callback": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["CallbackTestRequest"]
    response: components["schemas"]["ApiResponse_CallbackTestData_"]
  }
  "test_pipeline": {
    parameters: {
      path: {
        pipeline_id: string
        version: number
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["PipelineTestRequest"]
    response: components["schemas"]["ApiResponse_TaskDetail_"]
  }
  "update_api_key": {
    parameters: {
      path: {
        api_key_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["UpdateApiKeyRequest"]
    response: components["schemas"]["ApiResponse_ApiKeySummary_"]
  }
  "update_backend": {
    parameters: {
      path: {
        backend_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["UpdateBackendRequest"]
    response: components["schemas"]["ApiResponse_BackendDetail_"]
  }
  "update_stage_progress": {
    parameters: {
      path: {
        stage_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["StageProgressRequest"]
    response: components["schemas"]["ApiResponse_StageExecutionData_"]
  }
  "update_system_settings": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["UpdateSettingsRequest"]
    response: components["schemas"]["ApiResponse_SystemSettingsData_"]
  }
  "update_worker": {
    parameters: {
      path: {
        worker_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["UpdateWorkerRequest"]
    response: components["schemas"]["ApiResponse_WorkerDetail_"]
  }
  "upload_file": {
    parameters: {
      path: {}
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["Body_upload_file"]
    response: components["schemas"]["ApiResponse_UploadedFileDetail_"]
  }
  "upload_stage_artifact": {
    parameters: {
      path: {
        worker_id: string
        stage_id: string
      }
      query: {}
      header: {}
    }
    requestBody: components["schemas"]["Body_upload_stage_artifact"]
    response: components["schemas"]["ApiResponse_Artifact_"]
  }
  "validate_pipeline": {
    parameters: {
      path: {
        pipeline_id: string
        version: number
      }
      query: {}
      header: {}
    }
    requestBody: undefined
    response: components["schemas"]["ApiResponse_PipelineValidationData_"]
  }
}

export const operationSpecs = {
  "cancel_task": { method: "POST", path: "/api/v1/tasks/{task_id}/cancel" },
  "complete_stage": { method: "POST", path: "/internal/v1/workers/stages/{stage_id}/complete" },
  "create_api_key": { method: "POST", path: "/api/v1/management/api-keys" },
  "create_backend": { method: "POST", path: "/api/v1/management/backends" },
  "create_pipeline": { method: "POST", path: "/api/v1/management/pipelines" },
  "create_task": { method: "POST", path: "/api/v1/tasks" },
  "create_task_artifact_download_url": { method: "GET", path: "/api/v1/tasks/{task_id}/artifacts/{artifact_id}/download-url" },
  "delete_api_key": { method: "DELETE", path: "/api/v1/management/api-keys/{api_key_id}" },
  "download_task_artifact": { method: "GET", path: "/api/v1/tasks/{task_id}/artifacts/{artifact_id}/content" },
  "download_task_result": { method: "GET", path: "/api/v1/tasks/{task_id}/result/content" },
  "download_uploaded_file": { method: "GET", path: "/api/v1/files/{file_id}/content" },
  "download_worker_source_file": { method: "GET", path: "/internal/v1/workers/{worker_id}/files/{file_id}/content" },
  "drain_worker_self": { method: "POST", path: "/internal/v1/workers/{worker_id}/drain" },
  "get_api_key": { method: "GET", path: "/api/v1/management/api-keys/{api_key_id}" },
  "get_backend": { method: "GET", path: "/api/v1/management/backends/{backend_id}" },
  "get_callback_delivery": { method: "GET", path: "/api/v1/management/callbacks/{delivery_id}" },
  "get_capabilities": { method: "GET", path: "/api/v1/capabilities" },
  "get_dashboard_summary": { method: "GET", path: "/api/v1/management/dashboard/summary" },
  "get_health": { method: "GET", path: "/health" },
  "get_metrics": { method: "GET", path: "/metrics" },
  "get_pipeline": { method: "GET", path: "/api/v1/management/pipelines/{pipeline_id}/versions/{version}" },
  "get_readiness": { method: "GET", path: "/ready" },
  "get_system_info": { method: "GET", path: "/api/v1/system/info" },
  "get_system_settings": { method: "GET", path: "/api/v1/management/settings" },
  "get_task": { method: "GET", path: "/api/v1/tasks/{task_id}" },
  "get_task_result": { method: "GET", path: "/api/v1/tasks/{task_id}/result" },
  "get_task_stage": { method: "GET", path: "/api/v1/tasks/{task_id}/stages/{stage_id}" },
  "get_uploaded_file": { method: "GET", path: "/api/v1/files/{file_id}" },
  "get_worker": { method: "GET", path: "/api/v1/management/workers/{worker_id}" },
  "heartbeat_worker": { method: "POST", path: "/internal/v1/workers/heartbeat" },
  "initialize_default_catalog": { method: "POST", path: "/api/v1/management/defaults/initialize" },
  "lease_stages": { method: "POST", path: "/internal/v1/workers/lease" },
  "list_api_keys": { method: "GET", path: "/api/v1/management/api-keys" },
  "list_backends": { method: "GET", path: "/api/v1/management/backends" },
  "list_callback_attempts": { method: "GET", path: "/api/v1/management/callbacks/{delivery_id}/attempts" },
  "list_callback_deliveries": { method: "GET", path: "/api/v1/management/callbacks" },
  "list_events": { method: "GET", path: "/api/v1/events" },
  "list_pipelines": { method: "GET", path: "/api/v1/management/pipelines" },
  "list_task_artifacts": { method: "GET", path: "/api/v1/tasks/{task_id}/artifacts" },
  "list_task_events": { method: "GET", path: "/api/v1/tasks/{task_id}/events" },
  "list_task_stages": { method: "GET", path: "/api/v1/tasks/{task_id}/stages" },
  "list_tasks": { method: "GET", path: "/api/v1/tasks" },
  "list_workers": { method: "GET", path: "/api/v1/management/workers" },
  "publish_pipeline": { method: "POST", path: "/api/v1/management/pipelines/{pipeline_id}/versions/{version}/publish" },
  "reconcile_workers": { method: "POST", path: "/api/v1/management/workers/reconcile" },
  "register_worker": { method: "POST", path: "/internal/v1/workers/register" },
  "renew_stage_lease": { method: "POST", path: "/internal/v1/workers/stages/{stage_id}/renew" },
  "retry_callback_delivery": { method: "POST", path: "/api/v1/management/callbacks/{delivery_id}/retry" },
  "retry_task": { method: "POST", path: "/api/v1/tasks/{task_id}/retry" },
  "rotate_api_key": { method: "POST", path: "/api/v1/management/api-keys/{api_key_id}/rotate" },
  "route_task": { method: "POST", path: "/api/v1/management/tasks/{task_id}/route" },
  "run_retention_cleanup": { method: "POST", path: "/api/v1/management/maintenance/retention/run" },
  "start_stage": { method: "POST", path: "/internal/v1/workers/stages/{stage_id}/start" },
  "stream_events": { method: "GET", path: "/api/v1/events/stream" },
  "stream_task_events": { method: "GET", path: "/api/v1/tasks/{task_id}/events/stream" },
  "test_callback": { method: "POST", path: "/api/v1/management/callbacks/test" },
  "test_pipeline": { method: "POST", path: "/api/v1/management/pipelines/{pipeline_id}/versions/{version}/test" },
  "update_api_key": { method: "PATCH", path: "/api/v1/management/api-keys/{api_key_id}" },
  "update_backend": { method: "PATCH", path: "/api/v1/management/backends/{backend_id}" },
  "update_stage_progress": { method: "POST", path: "/internal/v1/workers/stages/{stage_id}/progress" },
  "update_system_settings": { method: "PATCH", path: "/api/v1/management/settings" },
  "update_worker": { method: "PATCH", path: "/api/v1/management/workers/{worker_id}" },
  "upload_file": { method: "POST", path: "/api/v1/files" },
  "upload_stage_artifact": { method: "POST", path: "/internal/v1/workers/{worker_id}/stages/{stage_id}/artifacts" },
  "validate_pipeline": { method: "POST", path: "/api/v1/management/pipelines/{pipeline_id}/versions/{version}/validate" },
} as const

export type OperationId = keyof operations
export type OperationResponse<T extends OperationId> = operations[T]["response"]
export type OperationRequestBody<T extends OperationId> = operations[T]["requestBody"]
